// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```Platform  Firebase App Id
// android   1:801522509613:android:ac91b0daad6980212815a4
// ios       1:801522509613:ios:a2ea7ea694fe6bed2815a4
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW-vpAFopdXkJFn_DuBvZNTFjip02IohU',
    appId: '1:801522509613:android:ac91b0daad6980212815a4',
    messagingSenderId: '801522509613',
    projectId: 'food-test-a19f9',
    storageBucket: 'food-test-a19f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQWNSfbXcBtdZ3QigdxurjcUiT_28MwTk',
    appId: '1:801522509613:ios:a2ea7ea694fe6bed2815a4',
    messagingSenderId: '801522509613',
    projectId: 'food-test-a19f9',
    storageBucket: 'food-test-a19f9.appspot.com',
    iosClientId: '801522509613-p95au18nbjbe2qi8ersdbchr2d394nds.apps.googleusercontent.com',
    iosBundleId: 'A',
  );
}




